version: '3.1'
services:
    database:
        image: postgres
        restart: always
        environment: 
            POSTGRES_USER: fastapi 
            POSTGRES_PASSWORD: 12345678
            POSTGRES_DB: fastdata
        volumes:
          - data:/var/lib/postgresql/data
        
    myappli:
        build:
          context: .
          dockerfile: Dockerfile
        depends_on:
          - database
        volumes:
          - .:/code
        ports:
          - 8000:8000
volumes:
    data:
